services:
  web:
    image: serch24/phpini
    ports:
      - 8001:80
    volumes:
      - ../prueba_fetch/post/:/var/www/html
    links:
      - mysql
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3333:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - ./lasBasesDeDatos:/var/lib/mysql
